### ISSUE TITLE
ScaffolderClient use 127.0.0.1 for backend url

### ISSUE THREAD

**Issue by levanvunam** [tduniec/backstage-timesaver-plugin#10]
Thanks for very cool plugins, I'm trying to integrate with the plugin but hitting the problem when deploying to Kubernetes

The error is
```
{"cause":{"cause":{"code":"UND_ERR_ABORTED","name":"AbortError"}},"level":"error","message":"Problem retriving response from url: http://127.0.0.1:7007/api/scaffolder/v2/tasks fetch failed","plugin":"timesaver","service":"backstage","stack":"TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11731:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ScaffolderClient.fetchTemplatesFromScaffolder (/app/node_modules/@tduniec/backstage-plugin-time-saver-backend/dist/index.cjs.js:417:24)\n    at async TimeSaverHandler.fetchTemplates (/app/node_modules/@tduniec/backstage-plugin-time-saver-backend/dist/index.cjs.js:473:26)\n    at async fn (/app/node_modules/@tduniec/backstage-plugin-time-saver-backend/dist/index.cjs.js:761:9)\n    at async TaskWorker.fn (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:607:9)\n    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:358:7)\n    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:306:31","type":"plugin"}
```

In my deploy env I'm not using 127.0.01, 

```
backend:
  baseUrl: https://myportal.com
```

Seems like ScaffolderClient hard code the url
```
async fetchTemplatesFromScaffolder() {
    const backendUrl = 'http://127.0.0.1:7007';
    const templatePath = '/api/scaffolder/v2/tasks';
    const callUrl = `${backendUrl}${templatePath}`;
    ...
```

Not sure if this is the root cause. What is possible solutions for this issue?

Thank you

**Comment by tduniec** [comment]
Hey, 

Yes, it was like this, since most of Backstage instances are coupled with backend. Let me check this

**Comment by tduniec** [comment]
Please can you tell me more about your config?
Do you have separate backend and separate frontend deployed in Kubernetes ? 
Are you using ? https://backstage.io/docs/auth/service-to-service-auth/ ? 
Did you configured the secret for service2service ?

**Comment by levanvunam** [comment]
Thanks for very fast response

- No I don't have separate backend and frontend, I used default setup which is all together
- Yes I use https://backstage.io/docs/auth/service-to-service-auth/ for service authentication and already config the backend secret.

I was suspecting the 127.0.0.1 is not accessible in my k8s pod, but when going inside the pod, and trying to curl the endpoint as 
`curl http://127.0.0.1:7007/api/scaffolder/v2/tasks`
seems to actually returning the data, but the data is around 500kb. I'm not sure that the data size could cause the task to be aborted. I check from command line seems quite fast

Thanks

**Comment by levanvunam** [comment]
I figure out the issues is due to the corporate proxy my cluster has. 

I did follow the document here https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md but the example seems not to work due to it didn't consider the NO_PROXY in the code

So have to use https://gist.github.com/zicklag/1bb50db6c5138de347c224fda14286da instead.

I share here just in case someone else having similar problems.

Thanks again for your help @tduniec
