### ISSUE TITLE
Unable to setup this plugin due to the use of deprecated package

### ISSUE THREAD

**Issue by Venkat279A** [tduniec/backstage-timesaver-plugin#31]
Hi @tduniec ,

When I tried to add the plugin package using the command: yarn add --cwd packages/app @tduniec/backstage-plugin-time- saver

I encounter the following error. Error couldn't find package "@types/react-chartjs-2@^2.5.7" required by "@tduniec/backstage- plugin-time-saver" on the npm registry.
 
 Upon researching the issue, I found this
<img width="896" alt="image" src="https://github.com/user-attachments/assets/85899f99-e481-4308-986d-0f8bb2446792">

--which is deprecated,and instead of @types/react-chartjs-2@ ^2.5.7 now its using react-chartis-2

Any assistance in resolving this issue would be greatly appreciated.

**Comment by tduniec** [comment]
Sorry for late response, did you manage to resolve the issue yourself? Is there any action required from us?

**Comment by Venkat279A** [comment]
Hi @tduniec,

Template is created and not able to fetch the template 
GET http://localhost:7007/api/scaffolder/v2/tasks/ net:: ERR_CONNECTION_REFUSED

Error:
TypeError

Message
Failed to fetch

Stack Trace:
TypeError: Failed to Fetch
