### ISSUE TITLE
scheduler need be configurable

### ISSUE THREAD

**Issue by blackholll** [tduniec/backstage-timesaver-plugin#41]
currently, the scheduler frequency is hardcode,  read the frequency from backstage configure maybe better.  if not provided, then use the default frequency

**Comment by tduniec** [comment]
Hello @blackholll 
https://github.com/tduniec/backstage-timesaver-plugin/blob/main/plugins/time-saver-backend/README.md#optional-configuration

Please find updated docs for this.

**Comment by blackholll** [comment]
@tduniec  it's so quickly.  thanks
