### ISSUE TITLE
Plugin data is hard to read when rendered in Dark Mode

### ISSUE THREAD

**Issue by jebentier** [tduniec/backstage-timesaver-plugin#6]
This project is very useful and I'd love to get my management team using this as a way to track ROI. I noticed that especially the chart colors, labels and some of the header text colors are not rendering well with the dark theme. Would it be possible to get this improved? 

Here's an example of what the plugin looks like when rendered in Dark Mode:
<img width="1483" alt="image" src="https://github.com/tduniec/backstage-timesaver-plugin/assets/571077/e1b6b2f3-12dd-4360-93de-0fb55daed42e">

**Comment by levanvunam** [comment]
it would be great if can adjust the color for this

**Comment by tduniec** [comment]
Hey Guys, 

I have improved a bit the visibility in dark mode. 
Unfortunately, working with react-chart-js line charts on their axis and legend had gave me a headache and as of now I couldn't find the way to change them. 
But for sure the improvement of visibility as of now is a step in right direction :) 

Please find updated package
@tduniec/backstage-plugin-time-saver@0.1.7 


Thanks a lot @levanvunam @jebentier 
I will plan to revisit this in the future
